[cosmic-ray]
module-path = "src/robotframework_construct/"
timeout = 5.0
excluded-modules = []
test-command = "uv run robot -L TRACE -P examples/bson/ -P examples/regmapmockup examples"

[cosmic-ray.distributor]
name = "local"
