[cosmic-ray]
module-path = "src/robotframework_construct/"
timeout = 5.0
excluded-modules = []
test-command = "uv run robot -L TRACE -P atests/regmapmockup/ -P atests/bson/ atests/"

[cosmic-ray.distributor]
name = "local"
