[cosmic-ray]
module-path = "src/robotframework_construct/__init__.py"
timeout = 5.0
excluded-modules = []
test-command = "uv run robot -L TRACE -P examples/bson/ examples/bson/bson.robot"

[cosmic-ray.distributor]
name = "local"
