[cosmic-ray]
module-path = "src/robotframework_construct/"
timeout = 7.5
excluded-modules = ["src/robotframework_construct/regmap.py"]
test-command = "sh -c 'uv run robot -L TRACE --exitonfailure -P atests/bson/ atests/dns && uv run pytest -x tests/__init__.py'"

[cosmic-ray.distributor]
name = "local"
