name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-robot-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.11, 3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv lock
        uv sync --extra test

    - name: Run Robot Framework tests
      run: |
        uv run robot -L TRACE -P atests/bson/ atests/bson/bson.robot
        uv run robot -L TRACE --variable bson_construct:compiled_document -P atests/bson/ atests/bson/bson.robot
        uv run robot -L TRACE -P atests/regmapmockup/ atests/regmapmockup/regmapmockup.robot
        uv run ruff check .
