name: CI_mutation_testing

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  run-robot-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install xonsh
        run: |
          uv tool install xonsh
  
      - name: Run mutation tests
        run: |
          uvx xonsh tasks/mutation_testing.sh
      
      - name: Upload cosmic ray log
        uses: actions/upload-artifact@v3
        with:
          name: cosmic_ray_log
          path: report_mutations*.html
